### ISSUE TITLE
Ability to choose input shapes

### ISSUE THREAD

**Issue by fxmarty** [huggingface/optimum-benchmark#1]
Currently, it is possible to choose the batch size, but it would be nice to be able to choose as well the sequence length (e.g. in text-classification, fill-mask, etc.).

**Comment by IlyasMoutawwakil** [comment]
@fxmarty it's possible now in inference benchmarks with `benchmark.input_shapes.sequence_length` (in cli or config file) for any shape control param in `optimum`'s [`DUMMY_INPUT_SHAPES`](https://github.com/huggingface/optimum/blob/1a5443b8ed8cd4ce1375055817ae6e75926939a6/optimum/utils/input_generators.py#L49)
