### ISSUE TITLE
How to evaluate a model that already exists locally and hasn't been uploaded yet, "model=?"

### ISSUE THREAD

**Issue by WCSY-YG** [huggingface/optimum-benchmark#102]
![微信截图_20231211144439](https://github.com/huggingface/optimum-benchmark/assets/89191003/51008a5a-ddf0-420e-a355-d9170ffb7dd6)
i really want to know how to load qwen model, thank you very much

**Comment by IlyasMoutawwakil** [comment]
just pass the the path of the model, also specify task because it can't be inferred in this case
