### ISSUE TITLE
what can I do when I have ConnectionError Error ; And I want to use my local llama weight ? 

### ISSUE THREAD

**Issue by cason0126** [huggingface/optimum-benchmark#104]
My error : 

omegaconf.errors.InterpolationResolutionError: ConnectionError raised while resolving interpolation: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/llama-2-model (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f61955893d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: df7e58f0-f23d-4dde-93b1-adac874d1acb)')

But i am already have llama weight in my local . 
how can i use it ? 
when i change  /examples/training-llamas/configs/_base_.yaml 
`defaults:
  - backend: pytorch # default backend
  - launcher: inline # default launcher
  - benchmark: training # default benchmark
  - experiment # inheriting from experiment config
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: llama-experiment
model: /data/7b
device: cuda

backend:
  no_weights: true
  torch_dtype: float16
  continuous_isolation: true

benchmark:
  warmup_steps: 40
  dataset_shapes:
    dataset_size: 160
    sequence_length: 256
  training_arguments:
    max_steps: 140
    per_device_train_batch_size: 1

hydra:
  run:
    dir: experiments/${oc.env:HOSTNAME}/${model}/${experiment_name}
  sweep:
    dir: experiments/${oc.env:HOSTNAME}/${model}/${experiment_name}
    subdir: ${benchmark.training_arguments.per_device_train_batch_size}
  job:
    chdir: true
    env_set:
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID
  sweeper:
    params:
      benchmark.training_arguments.per_device_train_batch_size: 1,2,4,8,16,32,64,128
      model: /data/7b`

My error is  ： 

![image](https://github.com/huggingface/optimum-benchmark/assets/35160064/4244152d-4e88-489e-80f6-e81a9269d930)

**Comment by IlyasMoutawwakil** [comment]
the error says that it's not possible to infer the task from a local directory, so you'll need to specify it with `task: text-generation`

**Comment by cason0126** [comment]
if i specify it with `task: text-generation ` 
Is not the task in the training that I want to evaluate, does that mean that the training task can't use local weights?

**Comment by IlyasMoutawwakil** [comment]
you can specify whatever task you want to use, `text-generation` just means that `AutoModelForCausalLM` is going to be used, it's equivalent to `language-modeling`

**Comment by IlyasMoutawwakil** [comment]
@cason0126 were you able to target your specific training task ?
