### ISSUE TITLE
Adding a config for SDXL including ORT fp16/etc optimization

### ISSUE THREAD

**Issue by poznano-amd** [huggingface/optimum-benchmark#106]
Hi!  I'm experimenting with `optimum-benchmark`, and I'm trying to add an ONNX Runtime fp16 inference config (GPU) for SDXL.  Looking for suggestions on the best approach.

In a standalone run outside of optimum-benchmark, we might use something like this:
```
optimum-cli export onnx --model stabilityai/stable-diffusion-xl-base-1.0 --task stable-diffusion-xl $DATA_DIR/sd_xl_base_onnx
python ${ORT_SD_DIR}/optimize_pipeline.py -i $DATA_DIR/sd_xl_base_onnx -o $DATA_DIR/sd_xl_base_fp16_1 --float16 <perhaps some other optimization flags too>
python ./run_ort_sdxl_txt2img.py
```

Note the use of ORT's [optimize_pipeline.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/optimize_pipeline.py) to export the fp16 model -- there's quite a bit of logic in there for the different parts of the overall model.  

There might be a few ways to accomplish this in optimum-benchmark:  

1. Use the steps above and point the benchmark yaml's `model` field to the path with the pre-optimized model (e.g. `$DATA_DIR/sd_xl_base_fp16_1` from above).  In this case, I see: `Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))`.  Is there some other fp16 backend config missing from the yaml?
2. Alternatively, let optimum-benchmark take care of the fp16 export/optimization.  However, the `auto_optimization_config.float16` method doesn't seem to be enough for SDXL. I think the (complex) logic in `optimize_pipeline.py` would probably need to be added to optimum-benchmark's ORT backend for SDXL.

Are you already running this type of config?  Suggestions on a path forward?

**Comment by IlyasMoutawwakil** [comment]
You can disable the export with `backend.export=false` and benchmark the optimized ONNX model by setting `model=$DATA_DIR/sd_xl_base_fp16_1`

**Comment by poznano-amd** [comment]
Quick clarification - I'm able to start a benchmarking run via `backend.export=false` along with `model=<path_to_optimized_model>`.

I'm pretty sure the issue I'm seeing is related to dependency changes after installing `optimum-benchmark` via this method:
> You can install optimum-benchmark using pip:
> 
> python -m pip install git+https://github.com/huggingface/optimum-benchmark.git

After installing this way, I'm no longer able to even run my standalone run_ort_sdxl_txt2img.py script without this error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))
```

Digging a bit deeper, it looks like my version of `optimum` gets upgraded when installing optimum-benchmark, so that is probably related to the underlying issue.  Still investigating...

**Comment by poznano-amd** [comment]
I think we have found the underlying issue.  We've been patching optimum's SDXL pipeline due to a known issue in the VAE decoder with fp16 optimization -- details in the commit here:  https://github.com/microsoft/onnxruntime/commit/af80542e65334979d3e37c1cb6c88068c5c65f3b

When we install `optimum-benchmark`, our patched version of `optimum` gets replaced, and that leads to the reported precision-related error.  This doesn't seem directly related to `optimum-benchmark`, so I'll close this issue.

**Comment by IlyasMoutawwakil** [comment]
Hi, thanks for investigating and reporting your experience with this issue.
I was going to investigate if some component of the diffusion pipeline outputs float16 and the next one expects float32, and it seems that was the issue, between vae encoder and decoder.
