### ISSUE TITLE
How to obtain the data from the 'forward' and 'generate' stages?

### ISSUE THREAD

**Issue by WCSY-YG** [huggingface/optimum-benchmark#126]
I used the same configuration file to test the model, but the results obtained are different from those of a month ago. In the result files from a month ago, data from both the forward and generate stages were included; however, the current generated result files only contain information from the prefill and decode stages. Here is the configuration file:

defaults:
  - backend: pytorch         # default backend
  - launcher: process        # default launcher
  - benchmark: inference     # default benchmark
  - experiment              # inheriting experiment schema
  - _self_                  # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog   # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_qwen7b
model: Qwen/Qwen-7B
device: cpu

launcher:
  device_isolation: true

benchmark:
  memory: true
  input_shapes:
    batch_size: 1
    sequence_length: 256
  new_tokens: 1000

hub_kwargs:
  trust_remote_code: true

hydra:
  run:
    dir: runs/${experiment_name}
  sweep:
    dir: sweeps/${experiment_name}
  job:
    chdir: true
    env_set:
      OVERRIDE_BENCHMARKS: 1
      CUDA_VISIBLE_DEVICES: 0
      CUDA_DEVICE_ORDER: PCI_BUS_ID

**Comment by IlyasMoutawwakil** [comment]
Hi, please use this branch https://github.com/huggingface/optimum-benchmark/tree/0.0.1 as the repo is currently being heavily refactored to add a Python API along the existing CLI, and unifying these two interfaces.

**Comment by IlyasMoutawwakil** [comment]
I added a link to the old version with a note in the readme.
If including forward and generate results in text generation benchmark reports is useful to you I can add them but I think prefill and decode make more sense. tell me if you want me to include it.

**Comment by WCSY-YG** [comment]
> prefill and decode

Thank you very much because initially, I wasn't quite clear about the relationship between them, which led me to ask this question. However, now I believe that 'prefill' and 'decode' should suffice for my purposes. Once again, thank you greatly.

**Comment by WCSY-YG** [comment]
> I added a link to the old version with a note in the readme. If including forward and generate results in text generation benchmark reports is useful to you I can add them but I think prefill and decode make more sense. tell me if you want me to include it.

Thank you very much because initially, I wasn't quite clear about the relationship between them, which led me to ask this question. However, now I believe that 'prefill' and 'decode' should suffice for my purposes. Once again, thank you greatly.
