### ISSUE TITLE
Trt llm surport question

### ISSUE THREAD

**Issue by lemon-little** [huggingface/optimum-benchmark#133]
The project shows that it supports trt llm, but the model NousResearch/Llama-2-7b-hf in the example trt_llama is not the engine file of trt_llama. When I built the model using trt llm and uploaded the generated engine file to huggingface for testing, a problem occurred.

**Comment by IlyasMoutawwakil** [comment]
Hi! trt-llm is supported through `optimum-nvidia` where the engine is created from HuggingFace Hub checkpoints.

**Comment by IlyasMoutawwakil** [comment]
the problem you're seeing is due to missing pretrained config in your repo

**Comment by lemon-little** [comment]
So，does Best Benchmark support images in this format? Among them, files such as `llama_float16_tp1_rank0.engine` are created by Tensorrt-LLM. 
![image](https://github.com/huggingface/optimum-benchmark/assets/53484050/1ce65cd3-b19d-4b2f-b03c-98d192d8fb78)

When I use the above `config.yaml` file to evaluate my Tensorrt-llm engine model like `joostinyi-baseten/llama7b-fp16-trtllm`, this error ` ModuleNotFoundError: No module named 'optimum.nvidia' ` appears. 

I still get this error after directly `pip install optimum`, and I directly `pip install optimum- nvidia ` shows that this library cannot be loaded. How can I solve it?

**Comment by lemon-little** [comment]
Hi！
Do I need to upload my `Tensert-llm engine` files like the `llama_float16_tp1_rank0.engine` in the picture to huggingface to evaluate my model? 
Or did I upload the wrong model file? What is the structure of the Tensorrt-llm model file supported by optimum-benchmark? 
Can you give me a correct huggingface model connection for the Tensorrt-llm model that is supported by optimization-benchmark?
I checked the content in `examples/trt_llama.yaml` and found that `model: NousResearch/Llama-2-7b-hf` is not a model in trt format.
After I use trt-llm to optimize my llm model, what should I do to use optimization-benchmark for evaluation?

I have encountered various errors so I have a lot of questions. I sincerely hope to get your reply. Thank you very much!

**Comment by IlyasMoutawwakil** [comment]
You should have a working optimum-nvidia environment, optimum-benchmark only benchmarks it, make sure you can load your model using https://github.com/huggingface/optimum-nvidia/tree/main

**Comment by lemon-little** [comment]
When I run the example of trt_llama, the following error appears
![d7a2c9095192d9f6654346b1412d400](https://github.com/huggingface/optimum-benchmark/assets/53484050/fb3aca45-a7c1-4fbd-b9e0-8515a94158b4)
![fe09a93194d8d07643c384449db68f1](https://github.com/huggingface/optimum-benchmark/assets/53484050/edb536e6-7d64-4574-b795-57af25fcf8f9)
How do I solve this problem?

**Comment by IlyasMoutawwakil** [comment]
make sure the example in https://github.com/huggingface/optimum-nvidia/tree/main?tab=readme-ov-file#generate works with your model, this seems like a problem with how you set up your model in the hub, please report errors related to the backend (trt-llm/optimum-nvidia) in [`optimum-nvidia`](https://github.com/huggingface/optimum-nvidia)

**Comment by IlyasMoutawwakil** [comment]
so apparently loading a trt-llm engine from the hub is still not supported in `optimum-nvidia`. closing this issue.
