### ISSUE TITLE
How to import and use the quantized model with AutoGPTQ？

### ISSUE THREAD

**Issue by jhrsya** [huggingface/optimum-benchmark#135]

**Comment by jhrsya** [comment]
I have already quantized the model with AutoGPTQ. How to import the model with optimum-benchmark?

**Comment by IlyasMoutawwakil** [comment]
Since AutoGPTQ models are supported with transformers, it should be as easy as setting the backend to `pytorch` in your config (or using `PyTorchConfig` in your code) and setting `model=your_model_absolute_path` with `device=cuda`.

**Comment by IlyasMoutawwakil** [comment]
Currently we're not testing local model loading (tests are loading models from the hub) but would love to review a PR with some local model loading sanity check

**Comment by jhrsya** [comment]
> Currently we're not testing local model loading (tests are loading models from the hub) but would love to review a PR with some local model loading sanity check

I have tested local model loading. It worked. Thankyou!
