### ISSUE TITLE
"Process PID not found" during "Running memory tracking"

### ISSUE THREAD

**Issue by andxalex** [huggingface/optimum-benchmark#154]
Hello,

First, thanks for this amazing resource! It's incredibly helpful!

I was running a simple script similar to the one in the examples folder. The script executes correctly but I'm unable to collect VRAM information during the memory tracking stage:

![image](https://github.com/huggingface/optimum-benchmark/assets/146676764/52a02e77-1e37-49fc-af7d-cff5a32992de)

I'm running through a docker container, using the "cuda.Dockerfile" image in the repo [here](https://github.com/huggingface/optimum-benchmark/blob/main/docker/cuda.dockerfile)

**Comment by IlyasMoutawwakil** [comment]
There seems to be a process that's executing on the [gpu device](https://github.com/huggingface/optimum-benchmark/blob/main/optimum_benchmark/trackers/memory.py#L211) but who's [info are not accessible](https://github.com/huggingface/optimum-benchmark/blob/main/optimum_benchmark/trackers/memory.py#L220).
I can see this happening in case your docker container doesn't have access to the host's pids.
You might consider adding `--pid=host` when running your container.

**Comment by franchukpetro** [comment]
@IlyasMoutawwakil in my case I'm running code in docker container of cloud provider. In the case I'm not able to specify docker run parameters, is there any other way to fix such issue?

**Comment by IlyasMoutawwakil** [comment]
Yes I believe there's something wrong with the way vram memory is measured now I started seeing the same errors in my logs. I will check it out.

**Comment by franchukpetro** [comment]
@IlyasMoutawwakil that is what cloud support answered me:

"But all the code should be running in the same container, so I don't see why you need access to the host process space."

They don't have an option to provide --pid=host for running container, so that seems to be not a solution for my case .

**Comment by IlyasMoutawwakil** [comment]
so this issue is related to nvidia drivers see https://github.com/NVIDIA/nvidia-docker/issues/179#issuecomment-597622063, basically what's happening is that when you run a docker container without `--pid=host`, whatever code you run on gpu within the container will show up (in best cases) on `nvidia-smi` as the pid of the docker container (or not at all), thus making it impossible to see the memory usage of specific processes within the container (for the gpu they're basically all the same process).

**Comment by IlyasMoutawwakil** [comment]
I can think of the following as solution, introducing an environment variable `GLOBAL_VRAM_MEASUREMENT="1"` which when set to 1, doesn't check the process specific memory usage and measures the global device memory usage using:
```python
device_handle = nvmlDeviceGetHandleByIndex(device_id)
global_used_vram = nvmlDeviceGetMemoryInfo(device_handle).used
```
this makes it possible to get the memory measurment by `pynvml`/`nvidia-smi` but only viable when you know that no one else is using your gpu device at the same time (shared resources).
@franchukpetro would you be interested in this feature ?

**Comment by IlyasMoutawwakil** [comment]
just added it as part of #156 and the results will looks like this on my machine
```bash
GLOBAL_VRAM_USAGE=1 optimum-benchmark --config-dir examples/ --config-name pytorch_timm
....
[PROC-0][2024-03-12 16:49:06,508][memory][INFO] -       + Tracking VRAM memory of CUDA devices: [0]
[PROC-0][2024-03-12 16:49:06,508][memory][INFO] -       + Tracking Allocated/Reserved memory of 1 Pytorch CUDA devices
[PROC-0][2024-03-12 16:49:06,508][inference][INFO] -    + Running memory tracking
tracking global VRAM usage. This will track the memory usage of all processes using the device(s).
[PROC-0][2024-03-12 16:49:15,607][memory][INFO] -               + forward max RAM memory: 857.153536 (MB)
[PROC-0][2024-03-12 16:49:15,607][memory][INFO] -               + forward max VRAM memory: 75356.962816 (MB)
[PROC-0][2024-03-12 16:49:15,607][memory][INFO] -               + forward max reserved memory: 195.035136 (MB)
[PROC-0][2024-03-12 16:49:15,607][memory][INFO] -               + forward max allocated memory: 168.565248 (MB)
```
notice the big VRAM usage because there's someone on another docker container using the GPU at the same time.

**Comment by franchukpetro** [comment]
I'm using vast.ai instances, and sadly there is no option to provide additional container argument. So, your workaround can be the only option for me, let me try it today. 

Do I understand correctly, I need to checkout to [this commit](https://github.com/huggingface/optimum-benchmark/pull/156/commits/7ade74fb58be3b31ea7aca2f79abda33e750cdba)? Will it be available in the stable version in the future, or do you plan to keep it as a separate version/separate commit for such cases as mine?

**Comment by IlyasMoutawwakil** [comment]
it will be merged today as part of the CI workflows migration. It's necessary for that PR as the new runners have the same PID namespaces issue.

**Comment by franchukpetro** [comment]
@IlyasMoutawwakil which environmental variable should I set to enable that?

I'm trying `TRACK_GLOBAL_VRAM="1"`, but logs also shows this:

![image](https://github.com/huggingface/optimum-benchmark/assets/35275869/3774d695-7467-47d5-8c85-b9ca5582cb4a)

So I also set `GLOBAL_VRAM_USAGE='1'`, but it hasn't helped as well.

**Comment by franchukpetro** [comment]
UPD:

Setting those two variables in .bashrc file wasn't helping, so I forced them to be set within python script for benchmarking:

```python
import os
os.environ["TRACK_GLOBAL_VRAM"] = "1"
os.environ["GLOBAL_VRAM_USAGE"] = "1"
```

And this finally resolved the issue with VRAM monitoring 🥳 :

![image](https://github.com/huggingface/optimum-benchmark/assets/35275869/53148b71-c03d-46e6-b538-72e3fa0521dd)

**Comment by IlyasMoutawwakil** [comment]
just `TRACK_GLOBAL_VRAM`, I still haven't cleaned up stuff, there's also the case with distributed inference/training where maximum VRAM should not be summed.

**Comment by IlyasMoutawwakil** [comment]
for env vars, use `export` or set them before `optimum-benchmark` like in the example :
`TRACK_GLOBAL_VRAM=1 optimum-benchmark --config-dir examples/ --config-name pytorch_timm`
or in the config file using `env_set` https://github.com/huggingface/optimum-benchmark/blob/main/examples/openvino_diffusion.yaml#L33

**Comment by IlyasMoutawwakil** [comment]
sorry It seems I replied with a typo, it's `PROCESS_SPECIFIC_VRAM=0` not `PECESS_SPECIFIC_VRAM=0`

**Comment by franchukpetro** [comment]
Thanks, that works!

![image](https://github.com/huggingface/optimum-benchmark/assets/35275869/9e8d60bc-1f18-4c69-b5fa-6c79b49684d1)
