### ISSUE TITLE
TensorRT-LLM - how to add support for new model?

### ISSUE THREAD

**Issue by pfk-beta** [huggingface/optimum-benchmark#164]
Hello,

I'm trying to run model ChatGLM, or Qwen or Bloom on TensorRT-LLM backend, but I'm getting NotImplemented exception or missing key. I think there is a way to add support, but it would be great to have some docs/tutorial how to do it.

**Comment by IlyasMoutawwakil** [comment]
currently in optimum-benchmark only llama is supported, however gemma, mistral and llama are supported were added lately in https://github.com/huggingface/optimum-nvidia/tree/main/src/optimum/nvidia/models
we can either add them here:
https://github.com/huggingface/optimum-benchmark/blob/e51c5d8de568f34a8db663d967a2e2e978c6a0de/optimum_benchmark/backends/tensorrt_llm/utils.py#L1
or start using the entry class `from optimum.nvidia import AutoModelForCausalLM`
don't hesitate to submit a PR.
