### ISSUE TITLE
BUG Report: Incorrect latency calculation for inference scenario with Tensor Parallel.

### ISSUE THREAD

**Issue by luzengxiangcn** [huggingface/optimum-benchmark#217]
Sample numbers are divided by world size in each GPU process.

optimum_benchmark/scenarios/inference/scenario.py Line 64.

``` python
       if is_torch_distributed_available() and torch.distributed.is_initialized():
            self.logger.info("\t+ Distributing batch size across processes")
            if self.config.input_shapes["batch_size"] % torch.distributed.get_world_size() != 0:
                raise ValueError(
                    "The batch size must be divisible by the number of processes in a distributed environment"
                )
            self.config.input_shapes["batch_size"] //= torch.distributed.get_world_size()
```

This part of code makes sure the total batch size is correct for replica inference mode (launcher=torchrun, disable tensor parallel),   , but for tensor parallel mode total batch size is no longer correct. The actual batch size is divided by world size, which results in incorrect throughput caculation.

optimum_benchmark/scenarios/inference/scenario.py. Line 406.
```python
  def atomic_prefill_volume(self) -> int:  # in tokens
      if {"input_ids", "prompt", "prompts"} & set(self.inputs.keys()):
          # text conditioned generation (1 bos token or sequence_length tokens)
          return self.config.input_shapes["batch_size"] * max(self.config.input_shapes["sequence_length"], 1)
      else:
          # image/audio conditioned generation (1 bos token)
          return self.config.input_shapes["batch_size"]
```

**Comment by IlyasMoutawwakil** [comment]
Yes thank you I only found out a few weeks ago and started fixing it before going on a vacation so it ended up taking time. I have a PR that I will submit today, I'll @ you to review it. My approach is to make the backend class aware of what kind of parallelism it has and use that info to either distribute inputs across replicas (dp) or havong the same input on all shards while forcing throughputs of ranks other than main one to 0 (that way summing throughputs from all processes still make sense).
