### ISSUE TITLE
LlamaCpp backend benchmark example code

### ISSUE THREAD

**Issue by Davidqian123** [huggingface/optimum-benchmark#282]
I want to do some benchmarks on GGUF models in terms of energy, latency, and memory using LlamaCpp backend, how to get started, any example code or instruction?

**Comment by IlyasMoutawwakil** [comment]
right here:

- [text embedding](https://github.com/huggingface/optimum-benchmark/blob/main/examples/llama_cpp_embedding.yaml)
- [text generation](https://github.com/huggingface/optimum-benchmark/blob/main/examples/llama_cpp_text_generation.yaml)

you can run these configs as explained in the [readme](https://github.com/huggingface/optimum-benchmark?tab=readme-ov-file#running-benchmarks-using-the-hydra-cli-)
