### ISSUE TITLE
Why llamaCpp only support batchsize=1 in text generation 

### ISSUE THREAD

**Issue by neozhang307** [huggingface/optimum-benchmark#283]
I wonder why there is such a limitation in llamacpp? 
`if self.config.task == "text-generation":`
 `           if input_shapes["batch_size"] != 1:`
`                raise ValueError("Batch size must be 1 for LlamaCpp text generation") 
`

In '/optimum_benchmark/backends/llama_cpp/backend.py'

**Comment by IlyasMoutawwakil** [comment]
@baptistecolle

**Comment by baptistecolle** [comment]
Hi,

Llama.cpp supports batch inference. However, we use a Python binding (`llama-cpp-python`) to interact with it, which currently does not support batch inference https://github.com/abetlen/llama-cpp-python/issues/771.

Once this feature is added, we can remove the current restriction and start benchmarking with batches

**Comment by neozhang307** [comment]
OK
