### ISSUE TITLE
DDP throughput

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [huggingface/optimum-benchmark#29]
@fxmarty should we multiply ddp throughput by the number of workers ?

**Comment by fxmarty** [comment]
Yes I think so!

**Comment by fxmarty** [comment]
For some reason transformers by default log only metrics for the rank=0: https://github.com/huggingface/transformers/blob/0ed23e4db26b0de01765c7d032002fe36702d357/src/transformers/trainer_pt_utils.py#L988-L1023

For now we do the same (https://github.com/huggingface/optimum-benchmark/blob/79dddc86a881627a57eae9e5095af2e7253a18cb/optimum_benchmark/backends/pytorch.py#L316), but I agree summing is better.

**Comment by fxmarty** [comment]
Actually tansformers trainer defines `num_train_samples = args.max_steps * total_train_batch_size`. My comment above is wrong.
