### ISSUE TITLE
How to Use a Local Model When Calling the Python API

### ISSUE THREAD

**Issue by WCSY-YG** [huggingface/optimum-benchmark#294]
![image](https://github.com/user-attachments/assets/ca4a11fc-29e5-4537-8e8a-95b309f43afe)

**Comment by IlyasMoutawwakil** [comment]
you need to specify the task and library manually, we don't officially support or test local models so happy to review a PR making it more robust (through testing or explicit error handling).

**Comment by IlyasMoutawwakil** [comment]
it seems that `huggingface_hub.repo_exists` raises an error if the passed argument is not of the form `user_namespace/repo_name`.

**Comment by IlyasMoutawwakil** [comment]
I fixed it in https://github.com/huggingface/optimum-benchmark/pull/299
