### ISSUE TITLE
Vision language model support

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/optimum-benchmark#295]
Hello! 💗 When trying to run benchmarks on vision language models (image-text-to-text) I realized this library doesn't support this task. It would be nice to have a support for it since these models are almost as mainstream as LLMs.

**Comment by IlyasMoutawwakil** [comment]
Hi, done 🤗 I remember giving you my word so had to do it 🔥
https://github.com/huggingface/optimum-benchmark/pull/296
I also added a small config for testing so that we can iterate and test it.
