### ISSUE TITLE
`FileNotFoundError` raised when calling `sysctl -n machdep.cpu.brand_string`

### ISSUE THREAD

**Issue by keyboardAnt** [huggingface/optimum-benchmark#3]
[This](https://github.com/huggingface/optimum-benchmark/blob/615bdae7fee17f5ba71a8e3c66006ccd217b54a5/src/utils.py#L66) results in https://app.warp.dev/block/NDK6NzeHhzHjb32CEAHlpB, although https://app.warp.dev/block/ujVpYSCSEJmXfMkODF8Bgt.

**Comment by IlyasMoutawwakil** [comment]
I believe this was fixed in https://github.com/huggingface/optimum-benchmark/pull/63
