### ISSUE TITLE
`whisper_benchmark.sh` seems broken

### ISSUE THREAD

**Issue by keyboardAnt** [huggingface/optimum-benchmark#4]
`whisper_benchmark.sh` [seems](https://app.warp.dev/block/3nd24PALTwcjVzaRwjhiWg) broken (I tried to follow https://github.com/huggingface/optimum-benchmark/blob/main/examples/whisper/README.md).

**Comment by IlyasMoutawwakil** [comment]
Hi @keyboardAnt, thanks for notifying me. Many features are being added day after day so the repo is currently constantly changing. The script failed because `benchmark.batch_size` became `benchmark.input_shapes.batch_size` for better control over input shapes.

**Comment by keyboardAnt** [comment]
Hi @IlyasMoutawwakil,

I only reached out because I liked your project and wanted to use it.

Since this repo is public, I assumed that at least its `main` branch is relatively stable. Perhaps it would be possible for you to use additional branches for development?

Thanks!

**Comment by IlyasMoutawwakil** [comment]
You're absolutely right! I will be adding some tests and CI next week especially for that. Thanks a lot for your interest in the project.

**Comment by IlyasMoutawwakil** [comment]
This was fixed long ago
