### ISSUE TITLE
Simulate GPTQ quantization

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [huggingface/optimum-benchmark#44]
Implement `GPTQQuantizer` to simulate quantized weights and get the expected performance measures.

**Comment by regisss** [comment]
Could you explain more what you mean by simulating GPTQ?

**Comment by IlyasMoutawwakil** [comment]
Right now a model can be loaded with GPTQ only if it's already quantized on the hub (like the Bloke repos). While BnB allows for zero shot quantization which is applied instantly.
GPTQ Quantization requires a real dataset for calibration (like c4)  but that takes a lot of time. So if someone wanna know how a model will perform (latency vs memory) in its GPTQ format, they should wait 2 or 4 GPU hours. The idea is to skip that with a dummy dataset (can be just one sentence) to get the quantized weights and perform latency, training throughput and memory measurements.

**Comment by regisss** [comment]
Ah okay makes sense, thanks!
