### ISSUE TITLE
Readme commands not working

### ISSUE THREAD

**Issue by shuyuelan** [huggingface/optimum-benchmark#6]
Setup as instruction said and run `python3 main.py --config-name bert`

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes-0.40.0.post3-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.40.0.post3-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/shuyuel/trt/build/x86_64-gnu'), PosixPath('/home/shuyuel/trt/build/x86_64-linux')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes-0.40.0.post3-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118.so...
[2023-07-13 21:41:37,464][benchmark][INFO] - Configuring inference benchmark
[2023-07-13 21:41:37,464][benchmark][INFO] -    + Setting seed(42)
[2023-07-13 21:41:37,973][backend][INFO] - Checking initial device isolation
Error executing job with overrides: []
Traceback (most recent call last):
  File "/benchmark/main.py", line 41, in run_experiment
    backend: Backend = backend_factory(
  File "/benchmark/src/backend/pytorch.py", line 60, in __init__
    super().__init__(model, device, cache_kwargs)
  File "/benchmark/src/backend/base.py", line 61, in __init__
    self.check_initial_isolation()
  File "/benchmark/src/backend/base.py", line 67, in check_initial_isolation
    check_no_process_is_running_on_cuda_device(
  File "/benchmark/src/utils.py", line 84, in check_no_process_is_running_on_cuda_device
    pids = [int(pid) for pid in subprocess.check_output(
  File "/benchmark/src/utils.py", line 84, in <listcomp>
    pids = [int(pid) for pid in subprocess.check_output(
ValueError: invalid literal for int() with base 10: ''

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by IlyasMoutawwakil** [comment]
Hi @shuyuelan yes I was only aware of this error today after adding some `bitsandbytes` support. Didn't notice it since there was always something running on some nvidia machine 😅. Thanks for reporting it!
