### ISSUE TITLE
RuntimeError: microsoft/deberta-large 

### ISSUE THREAD

**Issue by karthickai** [huggingface/optimum-benchmark#65]
When attempting to benchmark  DeBERTa (microsoft/deberta-large) model, I encountered the following error:
```
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0
```
Upon investigation, it seems that the `type_vocab_size` for the DeBERTa model is set to `0`, which causes the issue with `torch.randint`.

**Reproduction Steps**:
1. Set the model to microsoft/deberta-large.
2. Task: text-classification

optimum_benchmark/generators/task_generator.py line: 39
```python

def token_type_ids(self):
    return self.generate_random_integers(
        min_value=0,
        max_value=self.shapes["type_vocab_size"],
        shape=(
            self.shapes["batch_size"],
            self.shapes["sequence_length"],
        ),
    )
```

**Possible Solution**:
Consider adding a special case for models that do not have a valid `type_vocab_size`.

**Comment by IlyasMoutawwakil** [comment]
thank you! fixing it rn.
