### ISSUE TITLE
Issue with Colab notebook requiring but never using GPU

### ISSUE THREAD

**Issue by Tylersuard** [huggingface/optimum-benchmark#67]
Hello!  I have been using the Colab notebook you released a few weeks ago.  It is fast and it works well. However I often get the warning "You are connected to a GPU runtime but not using a GPU."  I tried to use a CPU runtime but the script requires a Cuda device to run.

**Comment by IlyasMoutawwakil** [comment]
Hi! I don't think that's related to the notebook, Colab tends to spam those warnings when you're not using the GPU continuously.

**Comment by Tylersuard** [comment]
I am looking at the GPU usage and it's a flat line at the bottom, it never goes up.  Also The embedding process is taking a bit longer than your results:

Cases uploaded: 7622
Uploading 126473
Embedding time: 5.838446617126465
{'upserted_count': 14}
Upload time: 1.2239892482757568
Cases uploaded: 7623
Uploading 126491
Embedding time: 6.212247133255005
{'upserted_count': 18}

I am using a T4 GPU, maybe that is the problem?

**Comment by Tylersuard** [comment]
A side question... I need to embed hundreds of millions of text chunks.  How can I do that quickly and cost-effectively?

**Comment by IlyasMoutawwakil** [comment]
I would highly suggest [text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference)
