### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [huggingface/optimum-benchmark#95]
Most of these features are covered in `examples` but not in the testing suite.
- Quantization schemes: 
  - Onnxruntime @aliabdelkader 
  - GPTQ @lopozz 
  - AWQ @aliabdelkader 
  - BnB @aliabdelkader 
- Optimizations:
  - FAv2
  - torch.compile. @aliabdelkader

**Comment by IlyasMoutawwakil** [comment]
@aliabdelkader yess I left these as first issues for anyone interested in contributing and having these settings tested as part of the CI. You just need to add a configuration and make sure that it's tested in the CI (might require adding some packages).

**Comment by aliabdelkader** [comment]
#take 
ok great, I am working on it.

**Comment by lopozz** [comment]
Hi @aliabdelkader and @IlyasMoutawwakil I benchmarked some GPTQ models in the past week and I'd be up to write a test for this quantization scheme if you're not already on it. Let me know

**Comment by IlyasMoutawwakil** [comment]
thanks ! would love to review the quantization configs ! make sure u include `backend.no_weights: true,false` when possible to ur sweep configs as the no weights feature is probably one of the most important features of `optimum-benchmark` and making sure it's always compatible with quantization schemes seems interesting

**Comment by aliabdelkader** [comment]
@lopozz no i did not work on that scheme yet. So, I would not mind if you want to write the test for it. 
@IlyasMoutawwakil sure, I will include the `backend.no_weights: true,false` sweep to the quantizatio test configs.

**Comment by lopozz** [comment]
Hi @IlyasMoutawwakil I was trying the same configuration file of #125 and I got this error 
```
AttributeError: 'LlamaRotaryEmbedding' object has no attribute 'cos_cached'
```
I believe it is caused by the newest refactoring. The last commit I see is  97e0b9e18a09ca3552f7d771cdfd3fa134c55a16 (more makefile stuff) of 4 days ago, so I believe I am working with the latest version. Should I open a new issue for this?

**Comment by IlyasMoutawwakil** [comment]
@lopozz I think it's a transformers issue https://github.com/unslothai/unsloth/issues/168#issuecomment-1943749354, try downgrading ur transformers version

**Comment by aliabdelkader** [comment]
Hi,

I just want to mention that I wont be able to work on the point related to FAv2 in case someone else wants to pick it up.
